### PR TITLE
Fix onGenericTrial() method error

### PR DESCRIPTION
**Pull request by alvaxet**
In order for the Carbon::now()->lt() method to work, it's supposed to have the Carbon instance as an argument

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why would ->trial_ends_at **not** be a Carbon instance already? It's in the `dates` array for subscriptons?

**Comment by alvaxet** [comment]
It's in User, I use this field for "generic trial", like here:
https://laravel.com/docs/5.2/billing#without-credit-card-up-front

From my migration:
```
Schema::table('users', function ($table) {
    $table->string('braintree_id')->nullable();
    $table->string('paypal_email')->nullable();
    $table->string('card_brand')->nullable();
    $table->string('card_last_four')->nullable();
**    $table->timestamp('trial_ends_at')->nullable();**
});
```

To populate it I use:
`
$user->trial_ends_at = Carbon::now()->addMonths(env('APP_TRIAL_MONTH'));
`
It comes from db to onGenericTrial method as string and causes error

**Comment by taylorotwell** [comment]
Do you have `trial_ends_at` in the "dates" array of your model though?

**Comment by alvaxet** [comment]
No, I didn't have it my dates array. When I put it there is works as expected, no fix needed. Thank you

**Pull request closed without merging**
